# Generated by Django 5.2.8 on 2025-11-08 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personagem', models.CharField(choices=[('universitario', 'Estudante Universitário'), ('empreendedor', 'Empreendedor Júnior'), ('aprendiz', 'Aprendiz Financeiro')], max_length=100)),
                ('avatar', models.CharField(default='🙂', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('idade', models.IntegerField(default=0)),
                ('pontuacao_total', models.IntegerField(default=0)),
                ('fase_atual', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
